    
language: ruby
rvm:
  - 2.4.0
before_install:
  - gem install bundler
before_script:
  - bundle exec bundle install
  - bundle exec rake db:migrate
script:
  - bundle exec cucumber
services:
  - redis-server