language: ruby
rvm:
  - 2.4.0
before_install:
  - gem install bundle
before_script:
  - bundle exec bundle install
  - bundle exec rake db:migrate
script:
  - bundle exec rspec
services:
  - redis-server