addons:
  postgresql: 9.6
  code_climate:
      repo_token: <Get from Code Climate>
after_success:
  - bundle exec codeclimate-test-reporter
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
dist: trusty
language: ruby
rvm:
  - 4.5.0
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec
services:
  - redis-server